- name: Deploy Webserver
  hosts: webservers
  become: true
  tasks:
    - name: Installing required packages
      apt:
        name: apache2
        state: latest
    - name: start webservice
      service:
        name: apache2
        state: started
        enabled: 'yes'
    - name: copy webpages to document root
      copy:
        src: /home/mbnhpe/index.html
        dest: /var/www/html/index.html
